/* Generated by re2c 0.13.5 on Wed Apr 25 17:01:06 2012 */
#line 1 "ext/cast/yylex.re"
/* -*- mode: c -*- */
/* Given to re2c to generate the lexer `yylex'.
 *
 * Based on c.re in the exmaples distributed with re2c.
 */
#include <string.h>
#include "cast.h"

/*
 * -------------------------------------------------------------------
 *                               Helpers
 * -------------------------------------------------------------------
 */

#define new_func(Foo)                                       \
VALUE cast_new_##Foo##_at(long pos) {                       \
  VALUE c##Foo;                                             \
  c##Foo = rb_const_get(cast_mC, rb_intern(#Foo));          \
  return rb_funcall2(c##Foo, rb_intern("new"), 0, NULL);    \
}
#define set_func(Foo, field)                                    \
VALUE cast_##Foo##_set_##field(VALUE self, VALUE value) {       \
  return rb_funcall2(self, rb_intern(#field "="), 1, &value);   \
}

new_func(IntLiteral);
set_func(IntLiteral, format);
set_func(IntLiteral, val);
set_func(IntLiteral, suffix);

new_func(FloatLiteral);
set_func(FloatLiteral, format);
set_func(FloatLiteral, val);
set_func(FloatLiteral, suffix);

new_func(CharLiteral);
set_func(CharLiteral, prefix);
set_func(CharLiteral, val);

new_func(StringLiteral);
set_func(StringLiteral, prefix);
set_func(StringLiteral, val);

/*
 * -------------------------------------------------------------------
 *                                yylex
 * -------------------------------------------------------------------
 */
#define BSIZE     8192

#define YYLTYPE VALUE

#define YYCTYPE   char
#define YYCURSOR  cursor
#define YYLIMIT   p->lim
#define YYMARKER  p->ptr
#define YYFILL(n) {}

#define RET(sym)      {p->cur = cursor; rb_ary_store(p->token, 0, sym); rb_ary_store(p->token, 1, sym  ); return;}
#define RETVALUE(sym) {p->cur = cursor; rb_ary_store(p->token, 0, sym); rb_ary_store(p->token, 1, value); return;}

/* Raise a ParseError.  `s' is the format string for the exception
 * message, which must contain exactly one '%s', which is replaced by
 * the string delimited by `b' and `e'.
 */
static void error1(char *s, char *b, char *e) {
  char *str;
  str = ALLOCA_N(char, e - b + 1);
  memcpy(str, b, e-b);
  str[e-b] = '\0';
  rb_raise(cast_eParseError, s, str);
}

/* `token' is assumed to be a two element array, which is filled in.
 */
void yylex(VALUE self, cast_Parser *p) {
  char *cursor = p->cur;
  char *cp;
  VALUE value;
 std:
  p->tok = cursor;
  #line 94 "ext/cast/yylex.re"

  
#line 88 "<stdout>"
{
	YYCTYPE yych;
	unsigned int yyaccept = 0;

	if ((YYLIMIT - YYCURSOR) < 11) YYFILL(11);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy76;
	case '\t':
	case '\v':
	case '\f':
	case ' ':	goto yy74;
	case '\n':	goto yy78;
	case '!':	goto yy50;
	case '"':	goto yy29;
	case '%':	goto yy40;
	case '&':	goto yy42;
	case '\'':	goto yy27;
	case '(':	goto yy62;
	case ')':	goto yy64;
	case '*':	goto yy38;
	case '+':	goto yy34;
	case ',':	goto yy58;
	case '-':	goto yy36;
	case '.':	goto yy25;
	case '/':	goto yy2;
	case '0':	goto yy22;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy24;
	case ':':	goto yy60;
	case ';':	goto yy52;
	case '<':	goto yy32;
	case '=':	goto yy48;
	case '>':	goto yy30;
	case '?':	goto yy72;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'h':
	case 'j':
	case 'k':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'x':
	case 'y':
	case 'z':	goto yy21;
	case '[':	goto yy66;
	case ']':	goto yy68;
	case '^':	goto yy44;
	case '_':	goto yy20;
	case 'a':	goto yy4;
	case 'b':	goto yy6;
	case 'c':	goto yy7;
	case 'd':	goto yy8;
	case 'e':	goto yy9;
	case 'f':	goto yy10;
	case 'g':	goto yy11;
	case 'i':	goto yy12;
	case 'l':	goto yy13;
	case 'r':	goto yy14;
	case 's':	goto yy15;
	case 't':	goto yy16;
	case 'u':	goto yy17;
	case 'v':	goto yy18;
	case 'w':	goto yy19;
	case '{':	goto yy54;
	case '|':	goto yy46;
	case '}':	goto yy56;
	case '~':	goto yy70;
	default:	goto yy80;
	}
yy2:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '*':	goto yy432;
	case '/':	goto yy430;
	case '=':	goto yy428;
	default:	goto yy3;
	}
yy3:
#line 254 "ext/cast/yylex.re"
	{ RET(cast_sym_DIV); }
#line 204 "<stdout>"
yy4:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy232;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	case 'u':	goto yy424;
	default:	goto yy5;
	}
yy5:
#line 137 "ext/cast/yylex.re"
	{
        value = rb_str_new(p->tok, cursor - p->tok);
        if (rb_funcall2(rb_funcall2(self, rb_intern("type_names"), 0, NULL),
                       rb_intern("include?"), 1, &value) == Qtrue) {
          RETVALUE(cast_sym_TYPENAME);
        } else {
          RETVALUE(cast_sym_ID);
        }
    }
#line 287 "<stdout>"
yy6:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy232;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	case 'r':	goto yy419;
	default:	goto yy5;
	}
yy7:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy232;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	case 'a':	goto yy400;
	case 'h':	goto yy401;
	case 'o':	goto yy402;
	default:	goto yy5;
	}
yy8:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy232;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	case 'e':	goto yy386;
	case 'o':	goto yy387;
	default:	goto yy5;
	}
yy9:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy232;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'm':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'y':
	case 'z':	goto yy233;
	case 'l':	goto yy372;
	case 'n':	goto yy373;
	case 'x':	goto yy374;
	default:	goto yy5;
	}
yy10:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy232;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'm':
	case 'n':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	case 'l':	goto yy364;
	case 'o':	goto yy365;
	default:	goto yy5;
	}
yy11:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy232;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	case 'o':	goto yy360;
	default:	goto yy5;
	}
yy12:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy232;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	case 'f':	goto yy350;
	case 'n':	goto yy352;
	default:	goto yy5;
	}
yy13:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy232;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	case 'o':	goto yy346;
	default:	goto yy5;
	}
yy14:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy232;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	case 'e':	goto yy326;
	default:	goto yy5;
	}
yy15:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy232;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 'u':
	case 'v':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	case 'h':	goto yy293;
	case 'i':	goto yy294;
	case 't':	goto yy295;
	case 'w':	goto yy296;
	default:	goto yy5;
	}
yy16:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy232;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'z':	goto yy233;
	case 'y':	goto yy286;
	default:	goto yy5;
	}
yy17:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy232;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	case 'n':	goto yy274;
	default:	goto yy5;
	}
yy18:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy232;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	case 'o':	goto yy263;
	default:	goto yy5;
	}
yy19:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy232;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	case 'h':	goto yy258;
	default:	goto yy5;
	}
yy20:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy232;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	case 'B':	goto yy235;
	case 'C':	goto yy236;
	case 'I':	goto yy237;
	default:	goto yy5;
	}
yy21:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '"':	goto yy131;
	case '\'':	goto yy232;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy5;
	}
yy22:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '.':	goto yy163;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy188;
	case 'E':
	case 'e':	goto yy166;
	case 'L':	goto yy168;
	case 'U':
	case 'u':	goto yy167;
	case 'X':
	case 'x':	goto yy187;
	case 'l':	goto yy169;
	default:	goto yy23;
	}
yy23:
#line 166 "ext/cast/yylex.re"
	{
        value = cast_new_IntLiteral_at(p->lineno);
        cast_IntLiteral_set_format(value, ID2SYM(rb_intern("dec")));
        cast_IntLiteral_set_val(value, LONG2NUM(strtol(p->tok, (char **)&cp, 10)));
        if (cp < cursor)
            cast_IntLiteral_set_suffix(value, rb_str_new(cp, cursor - cp));
        RETVALUE(cast_sym_ICON);
    }
#line 1459 "<stdout>"
yy24:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy165;
yy25:
	yyaccept = 2;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '.':	goto yy152;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy153;
	default:	goto yy26;
	}
yy26:
#line 247 "ext/cast/yylex.re"
	{ RET(cast_sym_DOT); }
#line 1484 "<stdout>"
yy27:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\'':	goto yy28;
	default:	goto yy143;
	}
yy28:
#line 282 "ext/cast/yylex.re"
	{
            rb_raise(cast_eParseError, "%d: unexpected character: %c (ASCII %d)\n", p->lineno, *p->tok, (int)*p->tok);
            goto std;
        }
#line 1498 "<stdout>"
yy29:
	yyaccept = 3;
	yych = *(YYMARKER = ++YYCURSOR);
	goto yy132;
yy30:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy125;
	case '>':	goto yy127;
	default:	goto yy31;
	}
yy31:
#line 257 "ext/cast/yylex.re"
	{ RET(cast_sym_GT); }
#line 1513 "<stdout>"
yy32:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '%':	goto yy115;
	case ':':	goto yy117;
	case '<':	goto yy121;
	case '=':	goto yy119;
	default:	goto yy33;
	}
yy33:
#line 256 "ext/cast/yylex.re"
	{ RET(cast_sym_LT); }
#line 1526 "<stdout>"
yy34:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '+':	goto yy111;
	case '=':	goto yy113;
	default:	goto yy35;
	}
yy35:
#line 252 "ext/cast/yylex.re"
	{ RET(cast_sym_ADD); }
#line 1537 "<stdout>"
yy36:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '-':	goto yy107;
	case '=':	goto yy109;
	case '>':	goto yy105;
	default:	goto yy37;
	}
yy37:
#line 251 "ext/cast/yylex.re"
	{ RET(cast_sym_SUB); }
#line 1549 "<stdout>"
yy38:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy103;
	default:	goto yy39;
	}
yy39:
#line 253 "ext/cast/yylex.re"
	{ RET(cast_sym_MUL); }
#line 1559 "<stdout>"
yy40:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy101;
	case '>':	goto yy99;
	default:	goto yy41;
	}
yy41:
#line 255 "ext/cast/yylex.re"
	{ RET(cast_sym_MOD); }
#line 1570 "<stdout>"
yy42:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '&':	goto yy95;
	case '=':	goto yy97;
	default:	goto yy43;
	}
yy43:
#line 248 "ext/cast/yylex.re"
	{ RET(cast_sym_AND); }
#line 1581 "<stdout>"
yy44:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy93;
	default:	goto yy45;
	}
yy45:
#line 258 "ext/cast/yylex.re"
	{ RET(cast_sym_XOR); }
#line 1591 "<stdout>"
yy46:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy91;
	case '|':	goto yy89;
	default:	goto yy47;
	}
yy47:
#line 259 "ext/cast/yylex.re"
	{ RET(cast_sym_OR); }
#line 1602 "<stdout>"
yy48:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy87;
	default:	goto yy49;
	}
yy49:
#line 242 "ext/cast/yylex.re"
	{ RET(cast_sym_EQ); }
#line 1612 "<stdout>"
yy50:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy85;
	default:	goto yy51;
	}
yy51:
#line 249 "ext/cast/yylex.re"
	{ RET(cast_sym_BANG); }
#line 1622 "<stdout>"
yy52:
	++YYCURSOR;
#line 237 "ext/cast/yylex.re"
	{ RET(cast_sym_SEMICOLON); }
#line 1627 "<stdout>"
yy54:
	++YYCURSOR;
#line 238 "ext/cast/yylex.re"
	{ RET(cast_sym_LBRACE); }
#line 1632 "<stdout>"
yy56:
	++YYCURSOR;
#line 239 "ext/cast/yylex.re"
	{ RET(cast_sym_RBRACE); }
#line 1637 "<stdout>"
yy58:
	++YYCURSOR;
#line 240 "ext/cast/yylex.re"
	{ RET(cast_sym_COMMA); }
#line 1642 "<stdout>"
yy60:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '>':	goto yy83;
	default:	goto yy61;
	}
yy61:
#line 241 "ext/cast/yylex.re"
	{ RET(cast_sym_COLON); }
#line 1652 "<stdout>"
yy62:
	++YYCURSOR;
#line 243 "ext/cast/yylex.re"
	{ RET(cast_sym_LPAREN); }
#line 1657 "<stdout>"
yy64:
	++YYCURSOR;
#line 244 "ext/cast/yylex.re"
	{ RET(cast_sym_RPAREN); }
#line 1662 "<stdout>"
yy66:
	++YYCURSOR;
#line 245 "ext/cast/yylex.re"
	{ RET(cast_sym_LBRACKET); }
#line 1667 "<stdout>"
yy68:
	++YYCURSOR;
#line 246 "ext/cast/yylex.re"
	{ RET(cast_sym_RBRACKET); }
#line 1672 "<stdout>"
yy70:
	++YYCURSOR;
#line 250 "ext/cast/yylex.re"
	{ RET(cast_sym_NOT); }
#line 1677 "<stdout>"
yy72:
	++YYCURSOR;
#line 260 "ext/cast/yylex.re"
	{ RET(cast_sym_QUESTION); }
#line 1682 "<stdout>"
yy74:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy82;
yy75:
#line 267 "ext/cast/yylex.re"
	{ goto std; }
#line 1690 "<stdout>"
yy76:
	++YYCURSOR;
#line 270 "ext/cast/yylex.re"
	{
            if(cursor == p->eof) RET(Qnil);
            goto std;
        }
#line 1698 "<stdout>"
yy78:
	++YYCURSOR;
#line 276 "ext/cast/yylex.re"
	{
            p->pos = cursor; ++p->lineno;
            goto std;
        }
#line 1706 "<stdout>"
yy80:
	yych = *++YYCURSOR;
	goto yy28;
yy81:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy82:
	switch (yych) {
	case '\t':
	case '\v':
	case '\f':
	case ' ':	goto yy81;
	default:	goto yy75;
	}
yy83:
	++YYCURSOR;
#line 264 "ext/cast/yylex.re"
	{ RET(cast_sym_RBRACKET); }
#line 1726 "<stdout>"
yy85:
	++YYCURSOR;
#line 236 "ext/cast/yylex.re"
	{ RET(cast_sym_NEQ); }
#line 1731 "<stdout>"
yy87:
	++YYCURSOR;
#line 235 "ext/cast/yylex.re"
	{ RET(cast_sym_EQEQ); }
#line 1736 "<stdout>"
yy89:
	++YYCURSOR;
#line 232 "ext/cast/yylex.re"
	{ RET(cast_sym_OROR); }
#line 1741 "<stdout>"
yy91:
	++YYCURSOR;
#line 225 "ext/cast/yylex.re"
	{ RET(cast_sym_OREQ); }
#line 1746 "<stdout>"
yy93:
	++YYCURSOR;
#line 224 "ext/cast/yylex.re"
	{ RET(cast_sym_XOREQ); }
#line 1751 "<stdout>"
yy95:
	++YYCURSOR;
#line 231 "ext/cast/yylex.re"
	{ RET(cast_sym_ANDAND); }
#line 1756 "<stdout>"
yy97:
	++YYCURSOR;
#line 223 "ext/cast/yylex.re"
	{ RET(cast_sym_ANDEQ); }
#line 1761 "<stdout>"
yy99:
	++YYCURSOR;
#line 265 "ext/cast/yylex.re"
	{ RET(cast_sym_RBRACE); }
#line 1766 "<stdout>"
yy101:
	++YYCURSOR;
#line 222 "ext/cast/yylex.re"
	{ RET(cast_sym_MODEQ); }
#line 1771 "<stdout>"
yy103:
	++YYCURSOR;
#line 220 "ext/cast/yylex.re"
	{ RET(cast_sym_MULEQ); }
#line 1776 "<stdout>"
yy105:
	++YYCURSOR;
#line 230 "ext/cast/yylex.re"
	{ RET(cast_sym_ARROW); }
#line 1781 "<stdout>"
yy107:
	++YYCURSOR;
#line 229 "ext/cast/yylex.re"
	{ RET(cast_sym_DEC); }
#line 1786 "<stdout>"
yy109:
	++YYCURSOR;
#line 219 "ext/cast/yylex.re"
	{ RET(cast_sym_SUBEQ); }
#line 1791 "<stdout>"
yy111:
	++YYCURSOR;
#line 228 "ext/cast/yylex.re"
	{ RET(cast_sym_INC); }
#line 1796 "<stdout>"
yy113:
	++YYCURSOR;
#line 218 "ext/cast/yylex.re"
	{ RET(cast_sym_ADDEQ); }
#line 1801 "<stdout>"
yy115:
	++YYCURSOR;
#line 263 "ext/cast/yylex.re"
	{ RET(cast_sym_LBRACE); }
#line 1806 "<stdout>"
yy117:
	++YYCURSOR;
#line 262 "ext/cast/yylex.re"
	{ RET(cast_sym_LBRACKET); }
#line 1811 "<stdout>"
yy119:
	++YYCURSOR;
#line 233 "ext/cast/yylex.re"
	{ RET(cast_sym_LEQ); }
#line 1816 "<stdout>"
yy121:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy123;
	default:	goto yy122;
	}
yy122:
#line 227 "ext/cast/yylex.re"
	{ RET(cast_sym_LSHIFT); }
#line 1826 "<stdout>"
yy123:
	++YYCURSOR;
#line 217 "ext/cast/yylex.re"
	{ RET(cast_sym_LSHIFTEQ); }
#line 1831 "<stdout>"
yy125:
	++YYCURSOR;
#line 234 "ext/cast/yylex.re"
	{ RET(cast_sym_GEQ); }
#line 1836 "<stdout>"
yy127:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '=':	goto yy129;
	default:	goto yy128;
	}
yy128:
#line 226 "ext/cast/yylex.re"
	{ RET(cast_sym_RSHIFT); }
#line 1846 "<stdout>"
yy129:
	++YYCURSOR;
#line 216 "ext/cast/yylex.re"
	{ RET(cast_sym_RSHIFTEQ); }
#line 1851 "<stdout>"
yy131:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy132:
	switch (yych) {
	case '"':	goto yy135;
	case '\\':	goto yy133;
	default:	goto yy131;
	}
yy133:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '"':
	case '\'':
	case '?':
	case '\\':
	case 'a':
	case 'b':
	case 'f':
	case 'n':
	case 'r':
	case 't':
	case 'v':	goto yy131;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy137;
	case 'x':	goto yy138;
	default:	goto yy134;
	}
yy134:
	YYCURSOR = YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy5;
	case 1: 	goto yy23;
	case 2: 	goto yy26;
	case 3: 	goto yy28;
	case 4: 	goto yy155;
	case 5: 	goto yy190;
	case 6: 	goto yy200;
	case 7: 	goto yy204;
	}
yy135:
	++YYCURSOR;
#line 203 "ext/cast/yylex.re"
	{
        value = cast_new_StringLiteral_at(p->lineno);
        if (p->tok[0] == '"') {
            cp = p->tok;
        } else {
            cast_StringLiteral_set_prefix(value, rb_str_new(p->tok, 1));
            cp = p->tok + 1;
        }
        cast_StringLiteral_set_val(value, rb_str_new(cp + 1, cursor - cp - 2));
        RETVALUE(cast_sym_SCON);
    }
#line 1915 "<stdout>"
yy137:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '"':	goto yy135;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy141;
	case '\\':	goto yy133;
	default:	goto yy131;
	}
yy138:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy139;
	default:	goto yy134;
	}
yy139:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '"':	goto yy135;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy139;
	case '\\':	goto yy133;
	default:	goto yy131;
	}
yy141:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '"':	goto yy135;
	case '\\':	goto yy133;
	default:	goto yy131;
	}
yy142:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy143:
	switch (yych) {
	case '\'':	goto yy149;
	case '\\':	goto yy144;
	default:	goto yy142;
	}
yy144:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '"':
	case '\'':
	case '?':
	case '\\':
	case 'a':
	case 'b':
	case 'f':
	case 'n':
	case 'r':
	case 't':
	case 'v':	goto yy142;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy145;
	case 'x':	goto yy146;
	default:	goto yy134;
	}
yy145:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\'':	goto yy149;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy151;
	case '\\':	goto yy144;
	default:	goto yy142;
	}
yy146:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy147;
	default:	goto yy134;
	}
yy147:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\'':	goto yy149;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy147;
	case '\\':	goto yy144;
	default:	goto yy142;
	}
yy149:
	++YYCURSOR;
#line 192 "ext/cast/yylex.re"
	{
        value = cast_new_CharLiteral_at(p->lineno);
        if (p->tok[0] == '\'') {
            cp = p->tok;
        } else {
            cast_CharLiteral_set_prefix(value, rb_str_new(p->tok, 1));
            cp = p->tok + 1;
        }
        cast_CharLiteral_set_val(value, rb_str_new(cp + 1, cursor - cp - 2));
        RETVALUE(cast_sym_CCON);
    }
#line 2130 "<stdout>"
yy151:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '\'':	goto yy149;
	case '\\':	goto yy144;
	default:	goto yy142;
	}
yy152:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy161;
	default:	goto yy134;
	}
yy153:
	yyaccept = 4;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy153;
	case 'E':
	case 'e':	goto yy156;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy157;
	default:	goto yy155;
	}
yy155:
#line 175 "ext/cast/yylex.re"
	{
        value = cast_new_FloatLiteral_at(p->lineno);
        cast_FloatLiteral_set_format(value, ID2SYM(rb_intern("dec")));
        cast_FloatLiteral_set_val(value, rb_float_new(strtod(p->tok, (char **)&cp)));
        if (cp < cursor)
            cast_FloatLiteral_set_suffix(value, rb_str_new(cp, cursor - cp));
        RETVALUE(cast_sym_FCON);
    }
#line 2180 "<stdout>"
yy156:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy158;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy159;
	default:	goto yy134;
	}
yy157:
	yych = *++YYCURSOR;
	goto yy155;
yy158:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy159;
	default:	goto yy134;
	}
yy159:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy159;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy157;
	default:	goto yy155;
	}
yy161:
	++YYCURSOR;
#line 215 "ext/cast/yylex.re"
	{ RET(cast_sym_ELLIPSIS); }
#line 2241 "<stdout>"
yy163:
	yyaccept = 4;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'E':
	case 'e':	goto yy179;
	default:	goto yy178;
	}
yy164:
	yyaccept = 1;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
yy165:
	switch (yych) {
	case '.':	goto yy163;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy164;
	case 'E':
	case 'e':	goto yy166;
	case 'L':	goto yy168;
	case 'U':
	case 'u':	goto yy167;
	case 'l':	goto yy169;
	default:	goto yy23;
	}
yy166:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy174;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy175;
	default:	goto yy134;
	}
yy167:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':	goto yy172;
	case 'l':	goto yy173;
	default:	goto yy23;
	}
yy168:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':	goto yy170;
	case 'U':
	case 'u':	goto yy171;
	default:	goto yy23;
	}
yy169:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy171;
	case 'l':	goto yy170;
	default:	goto yy23;
	}
yy170:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy171;
	default:	goto yy23;
	}
yy171:
	yych = *++YYCURSOR;
	goto yy23;
yy172:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':	goto yy171;
	default:	goto yy23;
	}
yy173:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy171;
	default:	goto yy23;
	}
yy174:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy175;
	default:	goto yy134;
	}
yy175:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy175;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy157;
	default:	goto yy155;
	}
yy177:
	yyaccept = 4;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
yy178:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy177;
	case 'E':
	case 'e':	goto yy183;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy157;
	default:	goto yy155;
	}
yy179:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy180;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy181;
	default:	goto yy134;
	}
yy180:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy181;
	default:	goto yy134;
	}
yy181:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy181;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy157;
	default:	goto yy155;
	}
yy183:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy184;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy185;
	default:	goto yy134;
	}
yy184:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy185;
	default:	goto yy134;
	}
yy185:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy185;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy157;
	default:	goto yy155;
	}
yy187:
	yych = *++YYCURSOR;
	switch (yych) {
	case '.':	goto yy201;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy198;
	default:	goto yy134;
	}
yy188:
	yyaccept = 5;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
	switch (yych) {
	case '.':	goto yy163;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy188;
	case 'E':
	case 'e':	goto yy166;
	case 'L':	goto yy192;
	case 'U':
	case 'u':	goto yy191;
	case 'l':	goto yy193;
	default:	goto yy190;
	}
yy190:
#line 155 "ext/cast/yylex.re"
	{
        value = cast_new_IntLiteral_at(p->lineno);
        cast_IntLiteral_set_format(value, ID2SYM(rb_intern("oct")));
        cast_IntLiteral_set_val(value, LONG2NUM(strtol(p->tok, (char **)&cp, 8)));
        if (cp < cursor) {
            if (cp[0] == '8' || cp[0] == '9')
                rb_raise(cast_eParseError, "bad octal digit: %c", cp[0]);
            cast_IntLiteral_set_suffix(value, rb_str_new(cp, cursor - cp));
        }
        RETVALUE(cast_sym_ICON);
    }
#line 2571 "<stdout>"
yy191:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':	goto yy196;
	case 'l':	goto yy197;
	default:	goto yy190;
	}
yy192:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':	goto yy194;
	case 'U':
	case 'u':	goto yy195;
	default:	goto yy190;
	}
yy193:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy195;
	case 'l':	goto yy194;
	default:	goto yy190;
	}
yy194:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy195;
	default:	goto yy190;
	}
yy195:
	yych = *++YYCURSOR;
	goto yy190;
yy196:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':	goto yy195;
	default:	goto yy190;
	}
yy197:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy195;
	default:	goto yy190;
	}
yy198:
	yyaccept = 6;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 4) YYFILL(4);
	yych = *YYCURSOR;
	switch (yych) {
	case '.':	goto yy210;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy198;
	case 'L':	goto yy213;
	case 'P':
	case 'p':	goto yy211;
	case 'U':
	case 'u':	goto yy212;
	case 'l':	goto yy214;
	default:	goto yy200;
	}
yy200:
#line 147 "ext/cast/yylex.re"
	{
        value = cast_new_IntLiteral_at(p->lineno);
        cast_IntLiteral_set_format(value, ID2SYM(rb_intern("hex")));
        cast_IntLiteral_set_val(value, LONG2NUM(strtol(p->tok, (char **)&cp, 16)));
        if (cp < cursor)
            cast_IntLiteral_set_suffix(value, rb_str_new(cp, cursor - cp));
        RETVALUE(cast_sym_ICON);
    }
#line 2664 "<stdout>"
yy201:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy202;
	default:	goto yy134;
	}
yy202:
	yyaccept = 7;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy202;
	case 'L':
	case 'l':	goto yy206;
	case 'P':
	case 'p':	goto yy205;
	default:	goto yy204;
	}
yy204:
#line 183 "ext/cast/yylex.re"
	{
        value = cast_new_FloatLiteral_at(p->lineno);
        cast_FloatLiteral_set_format(value, ID2SYM(rb_intern("hex")));
        cast_FloatLiteral_set_val(value, rb_float_new(strtod(p->tok, (char **)&cp)));
        if (cp < cursor)
            cast_FloatLiteral_set_suffix(value, rb_str_new(cp, cursor - cp));
        RETVALUE(cast_sym_FCON);
    }
#line 2736 "<stdout>"
yy205:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy207;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy208;
	default:	goto yy134;
	}
yy206:
	yych = *++YYCURSOR;
	goto yy204;
yy207:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy208;
	default:	goto yy134;
	}
yy208:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy208;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy206;
	default:	goto yy204;
	}
yy210:
	yyaccept = 7;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'P':
	case 'p':	goto yy224;
	default:	goto yy223;
	}
yy211:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy219;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy220;
	default:	goto yy134;
	}
yy212:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':	goto yy217;
	case 'l':	goto yy218;
	default:	goto yy200;
	}
yy213:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':	goto yy215;
	case 'U':
	case 'u':	goto yy216;
	default:	goto yy200;
	}
yy214:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy216;
	case 'l':	goto yy215;
	default:	goto yy200;
	}
yy215:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':
	case 'u':	goto yy216;
	default:	goto yy200;
	}
yy216:
	yych = *++YYCURSOR;
	goto yy200;
yy217:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'L':	goto yy216;
	default:	goto yy200;
	}
yy218:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy216;
	default:	goto yy200;
	}
yy219:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy220;
	default:	goto yy134;
	}
yy220:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy220;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy206;
	default:	goto yy204;
	}
yy222:
	yyaccept = 7;
	YYMARKER = ++YYCURSOR;
	if ((YYLIMIT - YYCURSOR) < 3) YYFILL(3);
	yych = *YYCURSOR;
yy223:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy222;
	case 'L':
	case 'l':	goto yy206;
	case 'P':
	case 'p':	goto yy228;
	default:	goto yy204;
	}
yy224:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy225;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy226;
	default:	goto yy134;
	}
yy225:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy226;
	default:	goto yy134;
	}
yy226:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy226;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy206;
	default:	goto yy204;
	}
yy228:
	yych = *++YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy229;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy230;
	default:	goto yy134;
	}
yy229:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy230;
	default:	goto yy134;
	}
yy230:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy230;
	case 'F':
	case 'L':
	case 'f':
	case 'l':	goto yy206;
	default:	goto yy204;
	}
yy232:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\'':	goto yy134;
	default:	goto yy143;
	}
yy233:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
yy234:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy5;
	}
yy235:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy254;
	default:	goto yy234;
	}
yy236:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy247;
	default:	goto yy234;
	}
yy237:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy238;
	default:	goto yy234;
	}
yy238:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy239;
	default:	goto yy234;
	}
yy239:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy240;
	default:	goto yy234;
	}
yy240:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy241;
	default:	goto yy234;
	}
yy241:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy242;
	default:	goto yy234;
	}
yy242:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy243;
	default:	goto yy234;
	}
yy243:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy244;
	default:	goto yy234;
	}
yy244:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'y':	goto yy245;
	default:	goto yy234;
	}
yy245:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy246;
	}
yy246:
#line 135 "ext/cast/yylex.re"
	{ RET(cast_sym_IMAGINARY); }
#line 3248 "<stdout>"
yy247:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy248;
	default:	goto yy234;
	}
yy248:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy249;
	default:	goto yy234;
	}
yy249:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy250;
	default:	goto yy234;
	}
yy250:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy251;
	default:	goto yy234;
	}
yy251:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'x':	goto yy252;
	default:	goto yy234;
	}
yy252:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy253;
	}
yy253:
#line 134 "ext/cast/yylex.re"
	{ RET(cast_sym_COMPLEX); }
#line 3350 "<stdout>"
yy254:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy255;
	default:	goto yy234;
	}
yy255:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy256;
	default:	goto yy234;
	}
yy256:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy257;
	}
yy257:
#line 133 "ext/cast/yylex.re"
	{ RET(cast_sym_BOOL); }
#line 3434 "<stdout>"
yy258:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy259;
	default:	goto yy234;
	}
yy259:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy260;
	default:	goto yy234;
	}
yy260:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy261;
	default:	goto yy234;
	}
yy261:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy262;
	}
yy262:
#line 130 "ext/cast/yylex.re"
	{ RET(cast_sym_WHILE); }
#line 3524 "<stdout>"
yy263:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy264;
	case 'l':	goto yy265;
	default:	goto yy234;
	}
yy264:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy272;
	default:	goto yy234;
	}
yy265:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy266;
	default:	goto yy234;
	}
yy266:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy267;
	default:	goto yy234;
	}
yy267:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy268;
	default:	goto yy234;
	}
yy268:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy269;
	default:	goto yy234;
	}
yy269:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy270;
	default:	goto yy234;
	}
yy270:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy271;
	}
yy271:
#line 129 "ext/cast/yylex.re"
	{ RET(cast_sym_VOLATILE); }
#line 3639 "<stdout>"
yy272:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy273;
	}
yy273:
#line 128 "ext/cast/yylex.re"
	{ RET(cast_sym_VOID); }
#line 3711 "<stdout>"
yy274:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy275;
	case 's':	goto yy276;
	default:	goto yy234;
	}
yy275:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy283;
	default:	goto yy234;
	}
yy276:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy277;
	default:	goto yy234;
	}
yy277:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy278;
	default:	goto yy234;
	}
yy278:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy279;
	default:	goto yy234;
	}
yy279:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy280;
	default:	goto yy234;
	}
yy280:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy281;
	default:	goto yy234;
	}
yy281:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy282;
	}
yy282:
#line 127 "ext/cast/yylex.re"
	{ RET(cast_sym_UNSIGNED); }
#line 3826 "<stdout>"
yy283:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy284;
	default:	goto yy234;
	}
yy284:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy285;
	}
yy285:
#line 126 "ext/cast/yylex.re"
	{ RET(cast_sym_UNION); }
#line 3904 "<stdout>"
yy286:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy287;
	default:	goto yy234;
	}
yy287:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy288;
	default:	goto yy234;
	}
yy288:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy289;
	default:	goto yy234;
	}
yy289:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy290;
	default:	goto yy234;
	}
yy290:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy291;
	default:	goto yy234;
	}
yy291:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy292;
	}
yy292:
#line 125 "ext/cast/yylex.re"
	{ RET(cast_sym_TYPEDEF); }
#line 4006 "<stdout>"
yy293:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy322;
	default:	goto yy234;
	}
yy294:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy312;
	case 'z':	goto yy313;
	default:	goto yy234;
	}
yy295:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy302;
	case 'r':	goto yy303;
	default:	goto yy234;
	}
yy296:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy297;
	default:	goto yy234;
	}
yy297:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy298;
	default:	goto yy234;
	}
yy298:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy299;
	default:	goto yy234;
	}
yy299:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy300;
	default:	goto yy234;
	}
yy300:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy301;
	}
yy301:
#line 124 "ext/cast/yylex.re"
	{ RET(cast_sym_SWITCH); }
#line 4122 "<stdout>"
yy302:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy308;
	default:	goto yy234;
	}
yy303:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy304;
	default:	goto yy234;
	}
yy304:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy305;
	default:	goto yy234;
	}
yy305:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy306;
	default:	goto yy234;
	}
yy306:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy307;
	}
yy307:
#line 123 "ext/cast/yylex.re"
	{ RET(cast_sym_STRUCT); }
#line 4218 "<stdout>"
yy308:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy309;
	default:	goto yy234;
	}
yy309:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy310;
	default:	goto yy234;
	}
yy310:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy311;
	}
yy311:
#line 122 "ext/cast/yylex.re"
	{ RET(cast_sym_STATIC); }
#line 4302 "<stdout>"
yy312:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy318;
	default:	goto yy234;
	}
yy313:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy314;
	default:	goto yy234;
	}
yy314:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy315;
	default:	goto yy234;
	}
yy315:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy316;
	default:	goto yy234;
	}
yy316:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy317;
	}
yy317:
#line 121 "ext/cast/yylex.re"
	{ RET(cast_sym_SIZEOF); }
#line 4398 "<stdout>"
yy318:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy319;
	default:	goto yy234;
	}
yy319:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy320;
	default:	goto yy234;
	}
yy320:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy321;
	}
yy321:
#line 120 "ext/cast/yylex.re"
	{ RET(cast_sym_SIGNED); }
#line 4482 "<stdout>"
yy322:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy323;
	default:	goto yy234;
	}
yy323:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy324;
	default:	goto yy234;
	}
yy324:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy325;
	}
yy325:
#line 119 "ext/cast/yylex.re"
	{ RET(cast_sym_SHORT); }
#line 4566 "<stdout>"
yy326:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy327;
	case 's':	goto yy329;
	case 't':	goto yy328;
	default:	goto yy234;
	}
yy327:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy340;
	default:	goto yy234;
	}
yy328:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy336;
	default:	goto yy234;
	}
yy329:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy330;
	default:	goto yy234;
	}
yy330:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy331;
	default:	goto yy234;
	}
yy331:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy332;
	default:	goto yy234;
	}
yy332:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy333;
	default:	goto yy234;
	}
yy333:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy334;
	default:	goto yy234;
	}
yy334:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy335;
	}
yy335:
#line 132 "ext/cast/yylex.re"
	{ RET(cast_sym_RESTRICT); }
#line 4688 "<stdout>"
yy336:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy337;
	default:	goto yy234;
	}
yy337:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy338;
	default:	goto yy234;
	}
yy338:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy339;
	}
yy339:
#line 118 "ext/cast/yylex.re"
	{ RET(cast_sym_RETURN); }
#line 4772 "<stdout>"
yy340:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy341;
	default:	goto yy234;
	}
yy341:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy342;
	default:	goto yy234;
	}
yy342:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy343;
	default:	goto yy234;
	}
yy343:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy344;
	default:	goto yy234;
	}
yy344:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy345;
	}
yy345:
#line 117 "ext/cast/yylex.re"
	{ RET(cast_sym_REGISTER); }
#line 4868 "<stdout>"
yy346:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy347;
	default:	goto yy234;
	}
yy347:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy348;
	default:	goto yy234;
	}
yy348:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy349;
	}
yy349:
#line 116 "ext/cast/yylex.re"
	{ RET(cast_sym_LONG); }
#line 4952 "<stdout>"
yy350:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy351;
	}
yy351:
#line 114 "ext/cast/yylex.re"
	{ RET(cast_sym_IF); }
#line 5024 "<stdout>"
yy352:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy355;
	case 't':	goto yy353;
	default:	goto yy234;
	}
yy353:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy354;
	}
yy354:
#line 115 "ext/cast/yylex.re"
	{ RET(cast_sym_INT); }
#line 5103 "<stdout>"
yy355:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy356;
	default:	goto yy234;
	}
yy356:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy357;
	default:	goto yy234;
	}
yy357:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy358;
	default:	goto yy234;
	}
yy358:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy359;
	}
yy359:
#line 131 "ext/cast/yylex.re"
	{ RET(cast_sym_INLINE); }
#line 5193 "<stdout>"
yy360:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy361;
	default:	goto yy234;
	}
yy361:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy362;
	default:	goto yy234;
	}
yy362:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy363;
	}
yy363:
#line 113 "ext/cast/yylex.re"
	{ RET(cast_sym_GOTO); }
#line 5277 "<stdout>"
yy364:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy368;
	default:	goto yy234;
	}
yy365:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy366;
	default:	goto yy234;
	}
yy366:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy367;
	}
yy367:
#line 112 "ext/cast/yylex.re"
	{ RET(cast_sym_FOR); }
#line 5361 "<stdout>"
yy368:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy369;
	default:	goto yy234;
	}
yy369:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy370;
	default:	goto yy234;
	}
yy370:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy371;
	}
yy371:
#line 111 "ext/cast/yylex.re"
	{ RET(cast_sym_FLOAT); }
#line 5445 "<stdout>"
yy372:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy383;
	default:	goto yy234;
	}
yy373:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy380;
	default:	goto yy234;
	}
yy374:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy375;
	default:	goto yy234;
	}
yy375:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy376;
	default:	goto yy234;
	}
yy376:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy377;
	default:	goto yy234;
	}
yy377:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy378;
	default:	goto yy234;
	}
yy378:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy379;
	}
yy379:
#line 110 "ext/cast/yylex.re"
	{ RET(cast_sym_EXTERN); }
#line 5553 "<stdout>"
yy380:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy381;
	default:	goto yy234;
	}
yy381:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy382;
	}
yy382:
#line 109 "ext/cast/yylex.re"
	{ RET(cast_sym_ENUM); }
#line 5631 "<stdout>"
yy383:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy384;
	default:	goto yy234;
	}
yy384:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy385;
	}
yy385:
#line 108 "ext/cast/yylex.re"
	{ RET(cast_sym_ELSE); }
#line 5709 "<stdout>"
yy386:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy394;
	default:	goto yy234;
	}
yy387:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	case 'u':	goto yy389;
	default:	goto yy388;
	}
yy388:
#line 106 "ext/cast/yylex.re"
	{ RET(cast_sym_DO); }
#line 5787 "<stdout>"
yy389:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy390;
	default:	goto yy234;
	}
yy390:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy391;
	default:	goto yy234;
	}
yy391:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy392;
	default:	goto yy234;
	}
yy392:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy393;
	}
yy393:
#line 107 "ext/cast/yylex.re"
	{ RET(cast_sym_DOUBLE); }
#line 5877 "<stdout>"
yy394:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy395;
	default:	goto yy234;
	}
yy395:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy396;
	default:	goto yy234;
	}
yy396:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy397;
	default:	goto yy234;
	}
yy397:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy398;
	default:	goto yy234;
	}
yy398:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy399;
	}
yy399:
#line 105 "ext/cast/yylex.re"
	{ RET(cast_sym_DEFAULT); }
#line 5973 "<stdout>"
yy400:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy416;
	default:	goto yy234;
	}
yy401:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy413;
	default:	goto yy234;
	}
yy402:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy403;
	default:	goto yy234;
	}
yy403:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy404;
	case 't':	goto yy405;
	default:	goto yy234;
	}
yy404:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy411;
	default:	goto yy234;
	}
yy405:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy406;
	default:	goto yy234;
	}
yy406:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy407;
	default:	goto yy234;
	}
yy407:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy408;
	default:	goto yy234;
	}
yy408:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy409;
	default:	goto yy234;
	}
yy409:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy410;
	}
yy410:
#line 104 "ext/cast/yylex.re"
	{ RET(cast_sym_CONTINUE); }
#line 6100 "<stdout>"
yy411:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy412;
	}
yy412:
#line 103 "ext/cast/yylex.re"
	{ RET(cast_sym_CONST); }
#line 6172 "<stdout>"
yy413:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy414;
	default:	goto yy234;
	}
yy414:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy415;
	}
yy415:
#line 102 "ext/cast/yylex.re"
	{ RET(cast_sym_CHAR); }
#line 6250 "<stdout>"
yy416:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy417;
	default:	goto yy234;
	}
yy417:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy418;
	}
yy418:
#line 101 "ext/cast/yylex.re"
	{ RET(cast_sym_CASE); }
#line 6328 "<stdout>"
yy419:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy420;
	default:	goto yy234;
	}
yy420:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy421;
	default:	goto yy234;
	}
yy421:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'k':	goto yy422;
	default:	goto yy234;
	}
yy422:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy423;
	}
yy423:
#line 100 "ext/cast/yylex.re"
	{ RET(cast_sym_BREAK); }
#line 6418 "<stdout>"
yy424:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy425;
	default:	goto yy234;
	}
yy425:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy426;
	default:	goto yy234;
	}
yy426:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy233;
	default:	goto yy427;
	}
yy427:
#line 99 "ext/cast/yylex.re"
	{ RET(cast_sym_AUTO); }
#line 6502 "<stdout>"
yy428:
	++YYCURSOR;
#line 221 "ext/cast/yylex.re"
	{ RET(cast_sym_DIVEQ); }
#line 6507 "<stdout>"
yy430:
	++YYCURSOR;
#line 97 "ext/cast/yylex.re"
	{ goto comment2; }
#line 6512 "<stdout>"
yy432:
	++YYCURSOR;
#line 96 "ext/cast/yylex.re"
	{ goto comment; }
#line 6517 "<stdout>"
}
#line 286 "ext/cast/yylex.re"


 comment:
  
#line 6524 "<stdout>"
{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 2) YYFILL(2);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy440;
	case '\n':	goto yy438;
	case '*':	goto yy436;
	default:	goto yy442;
	}
yy436:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '/':	goto yy443;
	default:	goto yy437;
	}
yy437:
#line 305 "ext/cast/yylex.re"
	{ goto comment; }
#line 6544 "<stdout>"
yy438:
	++YYCURSOR;
#line 292 "ext/cast/yylex.re"
	{
            p->tok = p->pos = cursor; ++p->lineno;
            goto comment;
        }
#line 6552 "<stdout>"
yy440:
	++YYCURSOR;
#line 298 "ext/cast/yylex.re"
	{
            if (cursor == p->eof)
              rb_raise(cast_eParseError,
                       "%d: unclosed multiline comment",
                       p->lineno);
        }
#line 6562 "<stdout>"
yy442:
	yych = *++YYCURSOR;
	goto yy437;
yy443:
	++YYCURSOR;
#line 290 "ext/cast/yylex.re"
	{ goto std; }
#line 6570 "<stdout>"
}
#line 306 "ext/cast/yylex.re"


 comment2:
  
#line 6577 "<stdout>"
{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) YYFILL(1);
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy449;
	case '\n':	goto yy447;
	default:	goto yy451;
	}
yy447:
	++YYCURSOR;
#line 311 "ext/cast/yylex.re"
	{
            p->tok = p->pos = cursor; ++p->lineno;
            goto std;
        }
#line 6594 "<stdout>"
yy449:
	++YYCURSOR;
#line 317 "ext/cast/yylex.re"
	{
            if (cursor == p->eof) RET(Qnil);
            goto std;
        }
#line 6602 "<stdout>"
yy451:
	++YYCURSOR;
#line 322 "ext/cast/yylex.re"
	{ goto comment2; }
#line 6607 "<stdout>"
}
#line 323 "ext/cast/yylex.re"

}
